package za.co.wirecard.channel.backoffice.entities;

import lombok.*;

import javax.persistence.*;

@Data
@Entity
@Table(name = "cardinal_auth", schema = "dbo", catalog = "transaction_db")
public class CardinalAuthEntity {
    @Id@Column(name = "id")
    private long id;
    @Basic@Column(name = "action_code")
    private String actionCode;
    @Basic@Column(name = "authorize_account")
    private Boolean authorizeAccount;
    @Basic@Column(name = "processor_order_id")
    private String processorOrderId;
    @Basic@Column(name = "processor_transaction_id")
    private String processorTransactionId;
    @Basic@Column(name = "reason_code")
    private String reasonCode;
    @Basic@Column(name = "reason_description")
    private String reasonDescription;
    @Basic@Column(name = "email_1")
    private String email1;
    @Basic@Column(name = "email_2")
    private String email2;
    @Basic@Column(name = "shipping_full_name")
    private String shippingFullName;
    @Basic@Column(name = "shipping_first_name")
    private String shippingFirstName;
    @Basic@Column(name = "shipping_middle_name")
    private String shippingMiddleName;
    @Basic@Column(name = "shipping_last_name")
    private String shippingLastName;
    @Basic@Column(name = "shipping_address_1")
    private String shippingAddress1;
    @Basic@Column(name = "shipping_address_2")
    private String shippingAddress2;
    @Basic@Column(name = "shipping_address_3")
    private String shippingAddress3;
    @Basic@Column(name = "shipping_city")
    private String shippingCity;
    @Basic@Column(name = "shipping_state")
    private String shippingState;
    @Basic@Column(name = "shipping_postal_code")
    private String shippingPostalCode;
    @Basic@Column(name = "shipping_country_code")
    private String shippingCountryCode;
    @Basic@Column(name = "shipping_phone_1")
    private String shippingPhone1;
    @Basic@Column(name = "shipping_phone_2")
    private String shippingPhone2;
    @Basic@Column(name = "billing_full_name")
    private String billingFullName;
    @Basic@Column(name = "billing_first_name")
    private String billingFirstName;
    @Basic@Column(name = "billing_middle_name")
    private String billingMiddleName;
    @Basic@Column(name = "billing_last_name")
    private String billingLastName;
    @Basic@Column(name = "billing_address_1")
    private String billingAddress1;
    @Basic@Column(name = "billing_address_2")
    private String billingAddress2;
    @Basic@Column(name = "billing_address_3")
    private String billingAddress3;
    @Basic@Column(name = "billing_city")
    private String billingCity;
    @Basic@Column(name = "billing_state")
    private String billingState;
    @Basic@Column(name = "billing_postal_code")
    private String billingPostalCode;
    @Basic@Column(name = "billing_country_code")
    private String billingCountryCode;
    @Basic@Column(name = "billing_phone_1")
    private String billingPhone1;
    @Basic@Column(name = "billing_phone_2")
    private String billingPhone2;
    @Basic@Column(name = "account_number")
    private String accountNumber;
    @Basic@Column(name = "expiration_month")
    private String expirationMonth;
    @Basic@Column(name = "expiration_year")
    private String expirationYear;
    @Basic@Column(name = "name_on_account")
    private String nameOnAccount;
    @Basic@Column(name = "card_code")
    private String cardCode;
    @Basic@Column(name = "error_number")
    private String errorNumber;
    @Basic@Column(name = "error_description")
    private String errorDescription;
    @Basic@Column(name = "order_id")
    private String orderId;
    @Basic@Column(name = "order_number")
    private String orderNumber;
    @Basic@Column(name = "type")
    private String type;
    @Basic@Column(name = "payment_reason_description")
    private String paymentReasonDescription;
    @Basic@Column(name = "enrolled")
    private String enrolled;
    @Basic@Column(name = "cavv")
    private String cavv;
    @Basic@Column(name = "eci_flag")
    private String eciFlag;
    @Basic@Column(name = "pa_res_status")
    private String paResStatus;
    @Basic@Column(name = "signature_verification")
    private String signatureVerification;
    @Basic@Column(name = "xid")
    private String xid;
    @Basic@Column(name = "ucaf_indicator")
    private String ucafIndicator;
    @Basic@Column(name = "acs_transaction_id")
    private String acsTransactionId;
    @Basic@Column(name = "three_ds_server_transaction_id")
    private String threeDsServerTransactionId;
    @Basic@Column(name = "ds_transaction_id")
    private String dsTransactionId;
    @Basic@Column(name = "authorization_payload")
    private String authorizationPayload;
    @Basic@Column(name = "cavv_algorithm")
    private String cavvAlgorithm;
    @Basic@Column(name = "challenge_cancel")
    private String challengeCancel;
    @Basic@Column(name = "three_ds_transaction_id")
    private long threeDsTransactionId;

}
